
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 84
#define YY_END_OF_BUFFER 85
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[240] =
    {   0,
        0,    0,    0,    0,    0,    0,   85,   83,   81,   82,
       82,   44,   83,   69,   70,   62,   59,   73,   60,   72,
       63,   39,   39,   75,   71,   56,   74,   54,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   76,   77,   83,   50,
       47,   47,   47,   45,   49,   53,   52,   52,   51,    0,
        0,   79,   42,   42,    0,    0,    0,    0,   39,   39,
        0,   78,   57,   58,   55,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   25,   80,   80,   80,
       80,   80,   21,   68,   80,   80,   80,   80,   80,    7,

       61,   80,   80,   80,   80,   80,   29,   80,   80,   80,
       80,   80,   80,   80,   48,   47,   46,   47,   43,    0,
        0,   42,    0,   38,    0,   37,    0,   42,   42,   66,
       80,   80,   80,   80,   36,   80,   36,   80,   80,   64,
       80,   80,   20,   80,   28,   80,   80,   80,   80,   65,
       18,   67,   80,   80,   80,   80,    6,   80,   80,   80,
        8,   80,   80,   80,    0,   42,   41,    0,   38,    0,
       40,   37,   37,   80,   80,   80,   26,   15,   80,   80,
       23,   80,   80,   80,   80,   80,    5,   80,   80,   80,
       32,   13,   80,   22,   34,    3,   80,   31,   80,   41,

        4,   19,   80,    2,   80,   35,   80,   80,   80,   80,
       80,   80,   80,   80,   24,   33,   80,   30,   80,   80,
       80,   17,   80,   80,   80,    9,   14,   16,   80,   12,
       80,   80,    1,   10,   80,   80,   27,   11,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    6,    6,    6,    6,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    6,    6,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   34,   35,   36,   37,   38,   39,
       34,   40,   41,   42,   43,   44,   45,   46,   47,   34,
       48,   49,   50,    6,   51,    6,   52,   53,   54,   55,

       56,   57,   58,   59,   60,   34,   34,   61,   62,   63,
       64,   65,   34,   66,   67,   68,   69,   70,   71,   72,
       73,   34,   74,    6,   75,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[76] =
    {   0,
        1,    1,    2,    1,    3,    3,    3,    4,    3,    3,
        3,    3,    3,    3,    5,    3,    6,    6,    6,    3,
        3,    3,    3,    3,    7,    8,    7,    7,    7,    8,
        9,    9,    9,    9,    9,    9,   10,    9,    9,   10,
        9,   10,    9,   10,    9,    9,    9,    3,    3,    3,
       11,    7,    8,    7,    7,    7,    8,    9,    9,    9,
        9,    9,   10,    9,    9,   10,    9,   10,    9,   10,
        9,    9,    9,    3,    3
    } ;

static const flex_int16_t yy_base[251] =
    {   0,
        0,    0,   73,   75,   80,   82,  698,  699,  699,  699,
      699,  699,  648,  699,  699,  699,  699,  699,  699,   72,
      699,   55,   77,  661,  699,   74,  699,  659,   62,   78,
      107,  103,   86,  113,  630,   63,  119,   66,  140,  143,
      110,   59,  139,  161,  135,  170,  699,  699,    0,  699,
      699,  699,  677,  699,  108,  699,  699,  699,  699,  640,
      606,  699,  188,  197,  596,  220,   88,  205,  228,  233,
      242,  699,  699,  699,  699,  561,  212,  215,  560,  218,
       80,  237,  240,  167,  234,  102,  219,  191,  245,  247,
      235,  242,  557,  260,  262,  266,  259,  264,  270,  555,

      554,  286,  278,  295,  285,  301,  552,  281,  300,  303,
      307,  313,  308,  551,  699,  699,  699,  598,  699,  592,
      358,  699,  163,  345,  581,  216,  361,  699,  170,  545,
      331,  333,  336,  345,  543,  357,  538,  348,  350,  536,
      352,  365,  534,  351,  353,  368,  376,  375,  378,  496,
      486,  484,  380,  403,  407,  310,  482,  386,  396,  399,
      480,  405,  412,  397,  455,  179,  442,  452,  460,  499,
      483,  224,  257,  394,  439,  435,  433,  431,  437,  438,
      402,  452,  458,  443,  456,  450,  400,  453,  466,  472,
      392,  387,  473,  361,  359,  356,  469,  339,  470,  479,

      293,  283,  490,  280,  489,  275,  492,  495,  500,  498,
      499,  508,  509,  517,  272,  268,  511,  243,  524,  516,
      525,  232,  533,  526,  535,  177,  162,  133,  527,  123,
      532,  541,   92,   89,  553,  559,   68,   58,  699,  615,
      626,  635,  646,  652,  657,  667,  675,  681,  684,  688
    } ;

static const flex_int16_t yy_def[251] =
    {   0,
      239,    1,  240,  240,  241,  241,  239,  239,  239,  239,
      239,  239,  242,  239,  239,  239,  239,  239,  239,  239,
      239,  243,  239,  239,  239,  239,  239,  239,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  239,  239,  245,  239,
      239,  239,  239,  239,  246,  239,  239,  239,  239,  239,
      247,  239,  239,  239,  239,  239,  248,  239,  239,  239,
      239,  239,  239,  239,  239,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,

      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  239,  239,  239,  239,  239,  247,
      239,  239,  239,  239,  249,  250,  239,  239,  239,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  239,  239,  239,  239,  239,  249,
      249,  250,  250,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  239,

      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,    0,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239
    } ;

static const flex_int16_t yy_nxt[775] =
    {   0,
        8,    9,   10,   11,    9,    8,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   35,   36,   35,   37,   38,   39,   40,   41,   42,
       43,   44,   35,   45,   46,   35,   35,   47,    8,   48,
       49,   29,   30,   31,   32,   33,   34,   35,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   35,   45,
       46,   35,   35,   50,    8,   52,   53,   52,   53,   54,
       66,   54,   57,   58,   57,   58,   62,  104,   63,   64,
       64,   68,   93,   69,   70,   70,   73,   74,   77,   94,

       67,   78,  125,   97,  122,   71,   80,   66,   79,   79,
      117,  118,   79,   79,  104,   81,   79,  133,   79,   93,
       88,   55,   89,   55,   77,   94,   67,   78,   79,   97,
       79,   82,   71,   80,   83,   86,   79,   90,   84,   79,
       87,   81,   79,  133,   85,  140,   88,   95,   89,  103,
       91,   96,   79,   79,   59,   92,   59,   79,   82,  110,
       79,   83,   86,   79,   90,   84,   87,  105,   98,   79,
       85,  140,  100,   79,   95,  103,   91,   99,   96,  167,
      167,   92,  101,   79,  102,   79,  110,  129,  129,   79,
       79,  138,  106,   79,  105,   98,  166,  166,  107,  100,

      108,  111,  112,   99,   64,   64,   64,  109,  101,  113,
      102,   79,   79,   64,   64,   64,  121,   79,  138,  106,
       79,   63,   64,   64,  107,  121,  108,   79,  111,  112,
      125,  142,  172,  109,  123,  113,  122,  124,  125,  130,
      172,   79,   68,  121,   69,   70,   70,   68,  132,   69,
       70,   70,  121,  127,  131,  127,   71,  142,  128,  129,
      129,   71,   79,  141,  134,   79,  130,   83,   79,   79,
      139,  125,  143,  172,  145,  132,  135,  136,  146,  137,
      131,  144,   79,   71,   79,   79,  150,   79,   71,  141,
       79,  134,   79,   79,   83,   79,  139,   79,  148,  143,

      145,  147,  135,  136,  146,  137,  149,  144,  151,   79,
       79,  152,   79,  150,   79,  154,   79,  153,   79,  155,
       79,  156,   79,  159,  148,   79,  157,  147,   79,  158,
       79,   79,  149,   79,  151,   79,   79,  152,  160,  162,
      164,  154,  161,   79,  153,   79,  155,  193,  156,  159,
       79,   79,  157,   79,  163,  174,  158,   79,   79,  168,
       79,  169,  169,   79,  160,  175,  162,  164,  161,  165,
      176,  165,  134,  193,  122,  166,  166,  128,  129,  129,
      163,   79,  174,   79,  135,  177,   79,  178,  180,   79,
      179,  182,  175,  181,  184,   79,  176,  183,   79,  134,

       79,   79,   79,   79,  185,  186,   79,   79,  188,   79,
      135,   79,  177,  178,  180,   79,  179,  182,   79,  187,
      181,  184,  194,  183,  195,   79,   79,  196,   79,  189,
       79,  185,  186,  190,  191,  188,   79,   79,  199,  197,
      201,  192,   79,  198,   79,  187,   79,   79,  194,   79,
       79,  195,   79,   79,  196,   79,  189,   79,  167,  167,
      190,  191,   79,  203,  199,  197,  201,  192,  200,  200,
      198,  122,  166,  166,  168,  202,  169,  169,  204,  205,
      206,   79,  207,   79,  208,   79,  209,   79,   79,   79,
      203,  210,  211,   79,  212,  200,  200,  215,  216,  170,

       79,  202,   79,   79,  204,  205,   79,  206,   79,  207,
      208,  213,  214,  209,  217,  170,   79,  210,  211,   79,
       79,  212,   79,   79,  215,  216,  218,  220,  221,  222,
       79,  219,   79,  225,   79,  224,   79,  213,  214,   79,
       79,  217,   79,  223,  226,   79,   79,  227,   79,   79,
       79,  228,  218,  229,  220,  221,  222,  219,   79,   79,
      225,   79,  224,  234,  230,  231,   79,   79,  232,  223,
      233,  226,  235,  227,   79,   79,   79,   79,  228,  229,
      236,  237,   79,   79,   79,   79,   79,  238,   79,  234,
      230,   79,  231,   79,  232,   79,  233,  170,  235,  119,

      117,   79,   79,   79,   79,   79,  236,   79,  237,   79,
       79,   79,  122,  119,  238,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   65,  119,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   76,   76,   76,
       76,   76,   76,  114,  114,  114,  114,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  120,  115,
       79,   75,  120,   72,  120,  126,  126,  126,  126,  171,
      171,  171,  173,  173,  173,  173,   61,  239,    7,  239,

      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239
    } ;

static const flex_int16_t yy_chk[775] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    4,    4,    3,
       22,    4,    5,    5,    6,    6,   20,   42,   20,   20,
       20,   23,   36,   23,   23,   23,   26,   26,   29,   36,

       22,   29,   67,   38,   67,   23,   30,   22,  238,   42,
       55,   55,   29,   36,   42,   30,   38,   81,  237,   36,
       33,    3,   33,    4,   29,   36,   22,   29,   30,   38,
       81,   31,   23,   30,   31,   32,   33,   34,   31,  234,
       32,   30,  233,   81,   31,   86,   33,   37,   33,   41,
       34,   37,   86,   32,    5,   34,    6,   31,   31,   45,
       41,   31,   32,   34,   34,   31,   32,   43,   39,   37,
       31,   86,   40,  230,   37,   41,   34,   39,   37,  123,
      123,   34,   40,  228,   40,   45,   45,  129,  129,   43,
       39,   84,   44,   40,   43,   39,  166,  166,   44,   40,

       44,   46,   46,   39,   63,   63,   63,   44,   40,   46,
       40,   44,  227,   64,   64,   64,   63,   84,   84,   44,
       46,   68,   68,   68,   44,   64,   44,  226,   46,   46,
      126,   88,  126,   44,   66,   46,   66,   66,  172,   77,
      172,   88,   69,   63,   69,   69,   69,   70,   80,   70,
       70,   70,   64,   71,   78,   71,   69,   88,   71,   71,
       71,   70,   77,   87,   82,   78,   77,   83,   80,   87,
       85,  173,   89,  173,   91,   80,   82,   82,   92,   83,
       78,   90,  222,   69,   85,   91,   97,   82,   70,   87,
       83,   82,   92,  218,   83,   89,   85,   90,   95,   89,

       91,   94,   82,   82,   92,   83,   96,   90,   98,   97,
       94,   99,   95,   97,   98,  103,   96,  102,  216,  104,
       99,  104,  215,  108,   95,  206,  105,   94,  103,  106,
      204,  108,   96,  202,   98,  105,  102,   99,  109,  111,
      113,  103,  110,  201,  102,  104,  104,  156,  104,  108,
      109,  106,  105,  110,  112,  131,  106,  111,  113,  124,
      156,  124,  124,  112,  109,  132,  111,  113,  110,  121,
      133,  121,  134,  156,  121,  121,  121,  127,  127,  127,
      112,  131,  131,  132,  134,  136,  133,  138,  141,  198,
      139,  144,  132,  142,  146,  134,  133,  145,  138,  134,

      139,  144,  141,  145,  147,  148,  196,  136,  153,  195,
      134,  194,  136,  138,  141,  142,  139,  144,  146,  149,
      142,  146,  158,  145,  159,  148,  147,  160,  149,  154,
      153,  147,  148,  154,  155,  153,  158,  192,  164,  162,
      174,  155,  191,  163,  174,  149,  159,  164,  158,  160,
      187,  159,  181,  154,  160,  162,  154,  155,  167,  167,
      154,  155,  163,  176,  164,  162,  174,  155,  168,  168,
      163,  165,  165,  165,  169,  175,  169,  169,  179,  180,
      182,  178,  183,  177,  184,  176,  185,  179,  180,  175,
      176,  186,  188,  184,  189,  200,  200,  197,  199,  171,

      186,  175,  182,  188,  179,  180,  185,  182,  183,  183,
      184,  190,  193,  185,  203,  170,  189,  186,  188,  197,
      199,  189,  190,  193,  197,  199,  205,  208,  209,  210,
      161,  207,  157,  213,  152,  212,  151,  190,  193,  205,
      203,  203,  207,  211,  214,  208,  150,  217,  210,  211,
      209,  219,  205,  220,  208,  209,  210,  207,  212,  213,
      213,  217,  212,  229,  221,  223,  220,  214,  224,  211,
      225,  214,  231,  217,  219,  221,  224,  229,  219,  220,
      232,  235,  231,  223,  143,  225,  140,  236,  137,  229,
      221,  232,  223,  135,  224,  130,  225,  125,  231,  120,

      118,  114,  107,  235,  101,  100,  232,   93,  235,  236,
       79,   76,   65,   61,  236,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  243,   60,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  244,  244,  244,
      244,  244,  244,  245,  245,  245,  245,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  247,   53,
       35,   28,  247,   24,  247,  248,  248,  248,  248,  249,
      249,  249,  250,  250,  250,  250,   13,    7,  239,  239,

      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[85] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1ostadio.l"
#line 2 "1ostadio.l"
	#include <stdio.h>
	#include <stdlib.h>
	#include <math.h>
	#include "syntax.tab.h"

    #define prints 1  


     char buffergiastring[254];       	                      
	 
	 void print_lexi(int token_id);
	 void yyerror(const char* err);

     void printakeraious(int token_id, int base);	
     int BinaryToInteger(char* str);
	 float BinaryToReal(char* str);		

	 void printpragmatikous(int token_id, int base);
	 int HexadecimalToInteger(char* str);	
	 float HexadecimalToReal(char* str);	

     int metritiserror=0; 

#line 748 "lex.yy.c"
/*mono ena arxeio gia input*/
/*peza=kefalaia*/
/*metritis gia grammes*/
/*upoanalites gia string kai comments*/

/*Regex gia ta Id Icons Rconst kai Cconst*/
#line 755 "lex.yy.c"

#define INITIAL 0
#define Stringsublexer 1
#define Commentsublexer 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 51 "1ostadio.l"

#line 53 "1ostadio.l"
 /*Desmedeumenes lexeis*/
#line 978 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 240 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 699 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 54 "1ostadio.l"
{ print_lexi(T_PROGRAM); return T_PROGRAM; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 55 "1ostadio.l"
{ print_lexi(T_CONST); return T_CONST; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 56 "1ostadio.l"
{ print_lexi(T_TYPE); return T_TYPE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 57 "1ostadio.l"
{ print_lexi(T_ARRAY); return T_ARRAY; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 58 "1ostadio.l"
{ print_lexi(T_LIST); return T_LIST; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 59 "1ostadio.l"
{ print_lexi(T_SET); return T_SET; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 60 "1ostadio.l"
{ print_lexi(T_OF); return T_OF; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 61 "1ostadio.l"
{ print_lexi(T_VAR); return T_VAR; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 62 "1ostadio.l"
{ print_lexi(T_RECORD); return T_RECORD; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 63 "1ostadio.l"
{ print_lexi(T_FUNCTION); return T_FUNCTION; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 64 "1ostadio.l"
{ print_lexi(T_PROCEDURE); return T_PROCEDURE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 65 "1ostadio.l"
{ print_lexi(T_INTEGER); return T_INTEGER; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 66 "1ostadio.l"
{ print_lexi(T_REAL); return T_REAL; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 67 "1ostadio.l"
{ print_lexi(T_BOOLEAN); return T_BOOLEAN; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 68 "1ostadio.l"
{ print_lexi(T_CHAR); return T_CHAR; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 69 "1ostadio.l"
{ print_lexi(T_FORWARD); return T_FORWARD; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 70 "1ostadio.l"
{ print_lexi(T_LENGTH); return T_LENGTH; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 71 "1ostadio.l"
{ print_lexi(T_NEW); return T_NEW; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 72 "1ostadio.l"
{ print_lexi(T_BEGIN); return T_BEGIN; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 73 "1ostadio.l"
{ print_lexi(T_END); return T_END; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 74 "1ostadio.l"
{ print_lexi(T_IF); return T_IF; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 75 "1ostadio.l"
{ print_lexi(T_THEN); return T_THEN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 76 "1ostadio.l"
{ print_lexi(T_ELSE); return T_ELSE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 77 "1ostadio.l"
{ print_lexi(T_WHILE); return T_WHILE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 78 "1ostadio.l"
{ print_lexi(T_DO); return T_DO; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 79 "1ostadio.l"
{ print_lexi(T_CASE); return T_CASE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 80 "1ostadio.l"
{ print_lexi(T_OTHERWISE); return T_OTHERWISE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 81 "1ostadio.l"
{ print_lexi(T_FOR); return T_FOR; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 82 "1ostadio.l"
{ print_lexi(T_TO); return T_TO; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 83 "1ostadio.l"
{ print_lexi(T_DOWNTO); return T_DOWNTO; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 84 "1ostadio.l"
{ print_lexi(T_WITH); return T_WITH; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 85 "1ostadio.l"
{ print_lexi(T_REAL); return T_READ; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 86 "1ostadio.l"
{ print_lexi(T_WRITE); return T_WRITE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 88 "1ostadio.l"
{ print_lexi(T_BCONST); return T_BCONST; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 89 "1ostadio.l"
{ print_lexi(T_BCONST); return T_BCONST; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 91 "1ostadio.l"
{ print_lexi(T_LISTFUNC); return T_LISTFUNC; } /*Prwta elegxo an einai list kai pio katw an einai Id  */
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 93 "1ostadio.l"
{ printakeraious(T_ICONST, 16); yylval.stringval = strdup(yytext);  return T_ICONST;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 94 "1ostadio.l"
{ printakeraious(T_ICONST, 2); yylval.stringval = strdup(yytext);  return T_ICONST;} 
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 95 "1ostadio.l"
{ printakeraious(T_ICONST, 10); yylval.stringval = strdup(yytext);  return T_ICONST;} 
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 98 "1ostadio.l"
{ printpragmatikous(T_RCONST, 16); yylval.stringval = strdup(yytext);  return T_RCONST; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 99 "1ostadio.l"
{ printpragmatikous(T_RCONST, 2); yylval.stringval = strdup(yytext);  return T_RCONST; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 100 "1ostadio.l"
{ printpragmatikous(T_RCONST, 10); yylval.stringval = strdup(yytext);  return T_RCONST; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 102 "1ostadio.l"
{ print_lexi(T_CCONST); yylval.stringval = strdup(yytext);  return T_CCONST; }
	YY_BREAK
/*Strings*/
case 44:
YY_RULE_SETUP
#line 106 "1ostadio.l"
{strcpy(buffergiastring, ""); BEGIN(Stringsublexer); }   
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 107 "1ostadio.l"
{ BEGIN(INITIAL);
                                if(strcmp(buffergiastring,"") ==0 ){    
                                    yyerror("Found empty String"); 
                                   } else {
                                    if(prints!=0) {
                                    printf("In line %d found string: '%s' (%d) \n", yylineno, buffergiastring, T_STRING); } yylval.stringval = strdup(yytext);  return T_STRING;}
                                }    
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 115 "1ostadio.l"
{ }                   
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 116 "1ostadio.l"
{                       /* Eidikoi xaraktires */
                        if(strlen(yytext) == 2) {
								if(strcmp(yytext, "\\n") == 0) {
									strcat(buffergiastring, "\n");
								} else if (strcmp(yytext, "\\t") == 0 ) {
									strcat(buffergiastring, "\t");
								} else if (strcmp(yytext, "\\r") == 0) {
									strcat(buffergiastring, "\r");
								} else if (strcmp(yytext, "\\f") == 0) {
									strcat(buffergiastring, "\f");
								} else if (strcmp(yytext, "\\b") == 0) {
									strcat(buffergiastring, "\b");
								} else if (strcmp(yytext, "\\v") == 0) {
									strcat(buffergiastring, "\v");
								} else {
									strcat(buffergiastring, &yytext[1]);
								}
							}else {             /* Otidipote allo */
								strcat(buffergiastring, yytext); 
							}
                        }
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 137 "1ostadio.l"
{ yyerror("New line without \\ \n"); }        /* Nea grammi xwris '\'   SFALMA */
	YY_BREAK
case YY_STATE_EOF(Stringsublexer):
#line 138 "1ostadio.l"
{ yyerror("End of string without closing \n"); } /* Anoixto string (Xwris na kleinoun ta ") SFALMA */
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 139 "1ostadio.l"
{ yyerror("Unrecognised Charachter \n"); }            /* Otidoipote allo SFALMA */
	YY_BREAK
/*Comments*/
case 50:
YY_RULE_SETUP
#line 144 "1ostadio.l"
{ if(prints!=0) { printf("Found comment\n");} BEGIN(Commentsublexer); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 145 "1ostadio.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 146 "1ostadio.l"
{} 				/* Nea grammi  */
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 147 "1ostadio.l"
{ }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 150 "1ostadio.l"
{ print_lexi(T_RELOP); return T_RELOP; }  
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 151 "1ostadio.l"
{ print_lexi(T_RELOP); return T_RELOP; }  
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 152 "1ostadio.l"
{ print_lexi(T_RELOP); return T_RELOP; }  
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 153 "1ostadio.l"
{ print_lexi(T_RELOP); return T_RELOP; }  
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 154 "1ostadio.l"
{ print_lexi(T_RELOP); return T_RELOP; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 156 "1ostadio.l"
{ print_lexi(T_ADDOP); return T_ADDOP; } 
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 157 "1ostadio.l"
{ print_lexi(T_ADDOP); return T_ADDOP; }    
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 159 "1ostadio.l"
{ print_lexi(T_OROP); return T_OROP; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 161 "1ostadio.l"
{ print_lexi(T_MULDIVANDOP); return T_MULDIVANDOP; } 
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 162 "1ostadio.l"
{ print_lexi(T_MULDIVANDOP); return T_MULDIVANDOP; } 
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 163 "1ostadio.l"
{ print_lexi(T_MULDIVANDOP); return T_MULDIVANDOP; } 
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 164 "1ostadio.l"
{ print_lexi(T_MULDIVANDOP); return T_MULDIVANDOP; } 
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 165 "1ostadio.l"
{ print_lexi(T_MULDIVANDOP); return T_MULDIVANDOP; } 
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 167 "1ostadio.l"
{ print_lexi(T_NOTOP); return T_NOTOP; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 169 "1ostadio.l"
{ print_lexi(T_INOP); return T_INOP; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 171 "1ostadio.l"
{ print_lexi(T_LPAREN); return T_LPAREN; } 
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 173 "1ostadio.l"
{ print_lexi(T_RPAREN); return T_RPAREN; } 
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 175 "1ostadio.l"
{ print_lexi(T_SEMI); return T_SEMI; } 
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 177 "1ostadio.l"
{ print_lexi(T_DOT); return T_DOT; } 
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 179 "1ostadio.l"
{ print_lexi(T_COMMA); return T_COMMA; } 
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 181 "1ostadio.l"
{ print_lexi(T_EQU); return T_EQU; } 
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 183 "1ostadio.l"
{ print_lexi(T_COLON); return T_COLON; } 
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 185 "1ostadio.l"
{ print_lexi(T_LBRACK); return T_LBRACK; } 
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 187 "1ostadio.l"
{ print_lexi(T_RBRACK); return T_RBRACK; } 
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 189 "1ostadio.l"
{ print_lexi(T_ASSIGN); return T_ASSIGN; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 191 "1ostadio.l"
{ print_lexi(T_DOTDOT); return T_DOTDOT; } 
	YY_BREAK
/*Anagnorizw edw ta id giati to regex tous tairiazei sta OR DIV MOD AND NOT HEAD TAIL*/
case 80:
YY_RULE_SETUP
#line 195 "1ostadio.l"
{ print_lexi(T_ID); yylval.stringval = strdup(yytext);  return T_ID; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 197 "1ostadio.l"
{}						
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 198 "1ostadio.l"
{} 				
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(Commentsublexer):
#line 199 "1ostadio.l"
{ print_lexi(T_EOF); return T_EOF; } 
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 200 "1ostadio.l"
{ yyerror("Unrecognised Charachter \n"); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 203 "1ostadio.l"
ECHO;
	YY_BREAK
#line 1508 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 240 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 240 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 239);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 203 "1ostadio.l"





void print_lexi(int token_id) {
    if(prints==0)return;
    printf("In line %d found token \'%s\' with number:(%d) \n", yylineno, yytext, token_id);
}
 //Metatropi akeraiou  apo tis vaseis se dekadiko 
void printakeraious(int token_id, int base){		
        int number;
        if(base == 2) number = BinaryToInteger(yytext);
        else if(base == 16) number = HexadecimalToInteger(yytext);
        else number = atoi(yytext);
        if(prints==0)return;
        printf("In line %d found number: %d (%s) from base [%d] with token number (%d) \n", yylineno, number, yytext, base, token_id);
    
}
 //Metatropi pragmatikou apo tis vaseis se dekadiko 
void printpragmatikous(int token_id, int base){
        float number;
        if(base == 2) number = BinaryToReal(yytext);
        else if(base == 16) number = HexadecimalToReal(yytext);
        else number = atof(yytext);
        if(prints==0)return;
        printf("In line %d found float: %f (%s) from base [%d] with token number (%d) \n", yylineno, number, yytext, base, token_id);
    
}


//Hex to Int
int HexadecimalToInteger(char *str){
    return (int) strtol(&str[2], NULL, 16);
}

//Bin to Int
int BinaryToInteger(char *str){
    return (int) strtol(&str[2], NULL, 2);
}

//Hex to Float
float HexadecimalToReal(char*str){
    float number = 0.0;
    int i,length_real;  
    char *character;
    character = strchr(str,'.');
    length_real = strlen(character)-1;
    number = (int)strtol(&str[2],&character,16);
    for(i=1;i<=length_real;i++){
        if(character[i] <= '9')
			number += (character[i] - '0') * (1/pow(16,i));
		else
			number += (character[i] + 10 - 'A') * (1/pow(16,i)); 
	}
    return number;
}

//Bin to Float
float BinaryToReal(char* str){
    float number = 0.0;
    int i,length_real;
    char *character;
    character = strchr(str,'.');
    length_real = strlen(character)-1;
    number = (int)strtol(&str[2],&character,2);
    for(i=1;i<=length_real;i++){
        number += (character[i] - '0') * (1/pow(2,i));
    }
    return number;
}
//Sunartisi gia ta Erros me Max errors ta 5
void yyerror(const char* err){
    metritiserror++;
    printf("ERROR - Line %d --> %s\n", yylineno, err);

    if(metritiserror == 5) {
        printf("MAXIMUM ERRORS FOUND\n");
        exit(EXIT_FAILURE);
    }
    yyless(1); /* Methodos panikou */
}
